spring.jpa.show-sql=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

wechat.miniprogram.appid=wxea65428847d4f791
wechat.miniprogram.secret=f00160ad946b0631dafdc43c33df181e

spring.profiles.active=prod
# spring.profiles.active=dev